- name: Delete Mapping Rule - {{delete_mapping_rule_name}}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.aac.mapping_rules.delete
    isamapi:
      name           : "{{ delete_mapping_rule_name }}"  
  notify: Commit Changes
